parameters:
    
    #Conección a MySQL
    database_driver: pdo_mysql
    database_host:   127.0.0.1
    database_port:   3306
    
    #Datos de la base de datos
    database_name:   wpv
    database_user:   root
    database_password: acceso
    
    
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 5f9829e32619356b6bd62d8a1300d16f
    database_path: null
